name: sync-repo

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
env:
  REPO1: headscale-demo
  GITEE_USER: ${{ secrets.GITEE_ACCOUNT }}
  GITEE_PASS: ${{ secrets.GITEE_PASSWORD }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://${{ env.GITEE_USER }}:${{ env.GITEE_PASS }}@gitee.com/${{ env.GITEE_USER }}/${{env.REPO1}}.git
          cd ${{ env.REPO1}}
          git pull --all
          git remote add github https://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@github.com/linai081795/headscale-demo.git
          git push -u -f --all github
