name: sync-repo

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '*/5 * * * *'
env:
  REPO1: headscale-demo
  GITEE_USER: ${{ secrets.GITEE_ACCOUNT }}
  GITEE_PASS: ${{ secrets.GITEE_PASSWORD }}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: repo-sync
        uses: actions/cache@v3
        with:
          path: repo
          key: repo-dir
      - name: sync
        uses: actions/checkout@v4
        with:
          repository: ${{env.GITEE_USER}}/${{ env.REPO1 }}
          path: repo/repo1
          github-server-url: https://gitee.com
          token: '${{ env.GITEE_USER }}:${{ env.GITEE_PASS }}'
          submodules: true
      - name: push
        run: |
          cd repo/repo1
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add github https://${{ secrets.GITHUB_TOKEN }}@github.com/linai081795/${{ env.REPO1 }}.git
          git push -u -f -all github
